const ACTIONS = {
  SET_TWEETS: "SET_TWEETS",
  SET_QUERY: "SET_QUERY",
  SET_HISTORY_SENTIMENT: "SET_HISTORY_SENTIMENT",
  SET_DATABASE_SNAPSHOT: "SET_DATABASE_SNAPSHOT",
  SET_ALERT_MESSAGE: "SET_ALERT_MESSAGE",
  SET_LIVE_QUERY: "SET_LIVE_QUERY",
};

export default ACTIONS;
